### ISSUE TITLE
Integrate new services in app

### ISSUE THREAD

**Issue by gupta1anubhav** [dsc-dtu/falcon-android#56]
We can use tiny.cc. Its documentation is present below

https://tiny.cc/api-docs

@firefinchdev Suggest other good services that we can integrate int our app

**Comment by firefinchdev** [comment]
![Screenshot_2019-06-16-00-10-32-429_com simolation urlshortener](https://user-images.githubusercontent.com/26357501/59556350-8944a600-8fde-11e9-83af-9ad25798ddb4.png)

**Comment by firefinchdev** [comment]
No need now.
