### ISSUE TITLE
can't write url in "long url" option

### ISSUE THREAD

**Issue by muhammadarif1** [dsc-dtu/falcon-android#57]

**Comment by firefinchdev** [comment]
Please provide the url that you were trying to write.

**Comment by muhammadarif1** [comment]
See the video below to make you more undestand

**Comment by muhammadarif1** [comment]
https://youtu.be/G0nxH0hPk5w

**Comment by firefinchdev** [comment]
Maybe something related to phone language. Which language is your phone using? Also, which keyboard app are you using?
Also, is it working after these steps:
1. Change phone lang to English
2. Completely stop url shortener (clear it from recents)
3. start app and try writing.
Also, try using other keyboard app and report

**Comment by firefinchdev** [comment]
Fixed f3d40b142b470d6f5ee17c6d2d5c4e7edda84b2f
